"""Added relation

Revision ID: 1e5d0b2a13f0
Revises: 6218cba85766
Create Date: 2025-05-21 14:52:10.558360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5d0b2a13f0'
down_revision: Union[str, None] = '6218cba85766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_types', sa.Column('part_type_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'device_types', 'part_types', ['part_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_types', type_='foreignkey')
    op.drop_column('device_types', 'part_type_id')
    # ### end Alembic commands ###
